### ISSUE TITLE
Newb question - request not found

### ISSUE THREAD

**Issue by bradgreens** [froatsnook/meteor-request#2]
I ran `meteor add froatsnook:request` just as the documentation shows.

The documentation does not show any usage of `import` and goes on to show immediate use of `request` examples.

In one of my imports, I have the following:

```
Meteor.methods( {
  'customData' () {
    const requestWithToken = request.defaults( {
      headers: {
        'API-Key': 'XXXXXX'
      }
    } );

    var data = requestWithToken.getSync( 'https://some-api.foo' )

    return data;
  }
} )
```

However in the console there is an error for the `request` method being undefined.

I've also tried `meteor npm install --save request`.

What am I missing?

edit: I was able to pull in the NPM module with `const request = require('request');`... but this is not the same tool as `meteor-request`, the APIs are different.

**Comment by froatsnook** [comment]
Hi.  I wrote this package before meteor 1.3 added import/export.  Let me explore this a bit!

**Comment by froatsnook** [comment]
OK, I added a note to the README about this.  Try this:

``` javascript
import { request } from "meteor/froatsnook:request";
```

You'll need to do that from all your server-side files that use `request`.

Please re-open if it doesn't work :).
